[package]
name = "erode-app"
version = "0.1.0"
description = "Ambient progressive rest reminder desktop app"
authors = ["r"]
edition = "2021"
rust-version = "1.89"

[lib]
name = "erode_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.6", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2.10.3", features = ["tray-icon", "image-ico", "image-png"] }
thiserror = "2"
tokio = { version = "1", features = ["sync", "time"] }
nalgebra = "0.34"
tracing = "0.1"
tauri-plugin-store = "2"
mimalloc = "*"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_UI_Accessibility"] }
spin_sleep = "1"

[target.'cfg(any(target_os = "macos", windows, target_os = "linux"))'.dependencies]
tauri-plugin-autostart = "2"
tauri-plugin-global-shortcut = "2"

[profile.dev]
incremental = true # Compile your binary in smaller steps.

[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
lto = true # Enables link-time-optimizations.
opt-level = 3 # Prioritizes small binary size. Use `3` if you prefer speed.
